name: blog-be image

on:
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/blog-be.yml"
      - "blog/be/**"
      - "!blog/be/README.md"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build image and publish
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: kamko/lnu_ht19_4me310_final_project_blog-be
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          workdir: blog/be
          snapshot: true
